export default {
  GENDER: ['MALE', 'FEMALE', 'UNANSWERED'],
  ADMIN: ["ACTIVATED", "DISACTIVATED"],
  MediaType: [
    'ADMIN_PROFILE',
    'COMPANY_LOGO',
    'COMPANY_PROFILE',
    'PROJECT_IMAGE',
    'USER_COVER_IMAGE',
    'USER_PROFILE_IMAGE',
    'ACHIEVEMENT_BANNER_IMAGE',
    'ACHIEVEMENT_PROFILE_IMAGE'
  ],
  USE_SCHEME_STATUS: ["INUSE"]
}
